Initial commit
aws-cloudformation/aws-cloudformation-resource-providers-cloudformation pull request #105
Opened 2023-02-13 16:56 UTC by yingxnin

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-13 20:10 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/ClientBuilder.java
> +  }
add a retry policy for throttling. here is an example: https://code.amazon.com/packages/AWSCloudFormationResourceProvidersEC2VPNGateway-TB/blobs/mainline/--/vpngateway/src/main/java/software/amazon/ec2/vpngateway/ClientBuilder.java#:~:text=Ec2Client%20ec2Client%3B-,private%20static%20final%20BackoffStrategy%20EC2_BACKOFF_THROTTLING_STRATEGY%20%3D,.build()%3B,-public%20static%20Ec2Client

2023-02-13 20:12 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/BaseHandlerStd.java
> +}
implement a handleError function like this to map the Exceptions to CFNExceptions https://code.amazon.com/packages/AWSCloudFormationResourceProvidersEC2VPNGateway-TB/blobs/mainline/--/vpngateway/src/main/java/software/amazon/ec2/vpngateway/BaseHandlerStd.java#:~:text=Logger%20logger)%3B-,protected%20ProgressEvent%3CResourceModel%2C%20CallbackContext%3E%20handleError(,%7D,-protected%20static%20String

2023-02-13 22:19 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                    if (model.getStackName() == null) {
check if model is null before doing a mode.getStackName() because can get a null exception if the user inputs an empty model for create

2023-02-13 22:21 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                .then(progress -> {
we can check if the StackName is null before invoking a progress event. So check the conditional before the call chain is started

2023-02-13 22:25 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                if (request.getDesiredResourceTags() != null && request.getDesiredResourceTags().size() != 0) {
for cleaner code we can make this a function inside of the Translator.java something like this: https://code.amazon.com/packages/AWSCloudFormationResourceProvidersElastiCache-TB/blobs/mainline/--/aws-elasticache-parametergroup/src/main/java/software/amazon/elasticache/parametergroup/Translator.java#:~:text=public%20static%20List,%7D

2023-02-14 15:28 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/ReadHandler.java
> +
for logging purporses add a logging statement like this: 
that includes the StackId, ClientToken

https://code.amazon.com/packages/AWSCloudFormationResourceProvidersEC2VPNGateway-TB/blobs/mainline/--/vpngateway/src/main/java/software/amazon/ec2/vpngateway/ReadHandler.java#:~:text=logger.log(String.format(%22%5BStackId%3A%20%25s%2C%20ClientRequestToken%3A%20%25s%5D%20Calling%20Read%20VPN%20Gateway%22%2C%20request.getStackId()%2C%20request.getClientRequestToken()))%3B

2023-02-15 17:06 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                            case CREATE_COMPLETE: {
need a CREATE_IN_PROGRESS check 
https://code.amazon.com/packages/AWS21Workflows/blobs/mainline/--/src/com/amazon/aws21/workflows/resources/cloudformation/stack/StackCreateWorkflowImpl.java#:~:text=%7D%20else%20if,%7D

2023-02-15 19:57 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +            .then(progress -> existenceCheck(progress,proxy, proxyClient, callbackContext, request, "AWS-CloudFormation-Stack::Delete::PreDeletionCheck", logger))
native code does not hae a pre-existence check: https://code.amazon.com/packages/AWS21Workflows/blobs/mainline/--/src/com/amazon/aws21/workflows/resources/cloudformation/stack/StackActivitiesImpl.java#:~:text=public%20ActivityReturnData%3CVoid%3E%20deleteStack,%7D

does the API throw a resourceNotFoundError if attempting a deletion on a resource that doesn't exist?

2023-02-15 19:58 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +                        DescribeStacksResponse describeStacksResponse;
put the stabilize in a function for easier to read code

2023-02-15 19:59 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +                        switch(status) {
need a DELETE_IN_PROGRESS case as in this stabilize function:

https://code.amazon.com/packages/AWS21Workflows/blobs/mainline/--/src/com/amazon/aws21/workflows/resources/cloudformation/stack/StackDeleteWorkflowImpl.java#:~:text=else%20if(,9%20years%20ago

2023-02-15 20:02 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress -> new ReadHandler().handleRequest(proxy, request, callbackContext, proxyClient, logger));
native code does not call a describe after an update is performed.

2023-02-16 16:11 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                if (request.getDesiredResourceTags() != null && request.getDesiredResourceTags().size() != 0) {
what about system tags? need to ensure those get merged and updated as well. here is an example: https://code.amazon.com/packages/AWSCloudFormationResourceProvidersEC2VPNGateway-TB/blobs/mainline/--/vpngateway/src/main/java/software/amazon/ec2/vpngateway/CreateHandler.java#:~:text=Map%3CString%2C%20String%3E%20mergedTags%20%3D,getSystemTags()).orElse(Collections.emptyMap()))%3B

2023-02-16 16:12 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                    .stabilize((awsRequest, awsResponse, client, _model, context) -> {
need to confirm with Andrew if a Stabilize is needed for your Create & Delete Handlers

2023-02-16 16:13 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress -> existenceCheck(progress,proxy, proxyClient, callbackContext, request,"AWS-CloudFormation-Stack::Update::PreUpdateCheck",logger))
is this pre-existence necessary? can the API call handle not found issues?

2023-02-16 16:14 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                    .stabilize((awsRequest, awsResponse, client, _model, context) -> {
again check if stabilization is needed here

2023-02-16 16:14 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress ->
need a call chain to update the tags. here is an example: https://code.amazon.com/packages/AWSCloudFormationResourceProvidersEC2VPNGateway-TB/blobs/mainline/--/vpngateway/src/main/java/software/amazon/ec2/vpngateway/UpdateHandler.java#:~:text=getDesiredResourceState()%2C%20callbackContext)-,.then(_progress%20%2D%3E%20tagsToRemove.isEmpty(),.progress()),-.then(progress

2023-02-16 16:15 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress -> new ReadHandler().handleRequest(proxy, request, callbackContext, proxyClient, logger));
you probably do not need a read handler call at the end and a stabilization.

2023-02-16 16:18 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +                            case DELETE_FAILED: throw new CfnNotStabilizedException(ResourceModel.TYPE_NAME, model.getStackId());
did you confirm that we want to throw an error instead of retrying the delete? 

"If a DELETE_FAILED state is reached, we can either retry the delete or we can surface an error message from the API call to the customer."

2023-02-16 16:19 UTC, ceskander-aws commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +            .then(progress -> new ReadHandler().handleRequest(proxy, request, callbackContext, proxyClient, logger));
probably do not need both stabilization and read handler calls

2023-02-16 21:14 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                if (request.getDesiredResourceTags() != null && request.getDesiredResourceTags().size() != 0) {
Update api handles the tag updates. we don't need to implement explicitly.

2023-02-17 00:54 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +            .then(progress -> new ReadHandler().handleRequest(proxy, request, callbackContext, proxyClient, logger));
confirmed that we need stabilization and read

2023-02-17 00:56 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress -> new ReadHandler().handleRequest(proxy, request, callbackContext, proxyClient, logger));
Confirmed we need stabilization and read

2023-02-17 00:57 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress ->
updateAPi handles the tag updates

2023-02-17 00:57 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                    .stabilize((awsRequest, awsResponse, client, _model, context) -> {
stabilization is needed.

2023-02-17 00:57 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +                    .stabilize((awsRequest, awsResponse, client, _model, context) -> {
stabilization is needed in those 2 handlers

2023-02-17 01:47 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +            .then(progress -> existenceCheck(progress,proxy, proxyClient, callbackContext, request, "AWS-CloudFormation-Stack::Delete::PreDeletionCheck", logger))
Confirmed that DeleteAPi doesn't support notFoundError. that means if we send a delete request to delete a deleted stack, the api will return success which not what we want.

2023-02-17 01:53 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            .then(progress -> existenceCheck(progress,proxy, proxyClient, callbackContext, request,"AWS-CloudFormation-Stack::Update::PreUpdateCheck",logger))
yes, we can remove this pre-existence check for update api

2023-02-17 19:20 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +                            case DELETE_FAILED: throw new CfnNotStabilizedException(ResourceModel.TYPE_NAME, model.getStackId());
Confirmed with Andrew, We don't retry.

2023-03-07 20:11 UTC, aygold92 requested changes

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +  "readOnlyProperties": [
There's a lot more readOnlyProperties than you have listed.  Outputs, CreationTime, etc. (there's a bunch more)

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +  "required": [
you can add a lot of additional validation logic using oneOf, etc.

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +public class CreateHandler extends BaseHandlerStd {
like mentioned above, I think we need to add TerminationProtection and StackPolicy APIs. Same with Update.

On delete, I guess you should NOT disable TerminationProtection.  They'll have to first do an update to remove TerminationProtection, which is the current behavior using CFN

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            case UPDATE_COMPLETE_CLEANUP_IN_PROGRESS: return true;
why is CLEANUP_IN_PROGRESS considered stabilized?

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            case UPDATE_FAILED:
when would it be in UPDATE_FAILED?  Wouldn't that be before it rolls back?

We need to wait for it to finish rolling back or finish updating entirely

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +        logger.log(String.format("[StackId: %s, ClientRequestToken: %s] Calling Update VPN Gateway", request.getStackId(), request.getClientRequestToken()));
Copy paste error i'm guess :) (VPN Gateway)

2023-03-07 20:11 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/ReadHandler.java
> +public class ReadHandler extends BaseHandlerStd {
I think you need GetStackPolicy

2023-03-07 20:17 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                return false;
In these progress events, you probably want to return a message with the stack status as well as a "NotStabilized" error code (even with the IN_PROGRESS event).  That way, it'll be easy to see when customers are polling for the resource status using [GetResourceRequestStatus](https://docs.aws.amazon.com/cloudcontrolapi/latest/APIReference/API_GetResourceRequestStatus.html)

2023-03-14 21:27 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                return false;
As we discussed, we will not do anything to it.

2023-03-14 21:27 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/ReadHandler.java
> +public class ReadHandler extends BaseHandlerStd {
Added GetStackPolicy in the readHandler

2023-03-14 21:28 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            case UPDATE_FAILED:
As discussed, we will keep this but I do add a comment on why we keep UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS

2023-03-14 21:29 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +            case UPDATE_COMPLETE_CLEANUP_IN_PROGRESS: return true;
same as below

2023-03-14 21:30 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +public class CreateHandler extends BaseHandlerStd {
TerminationProtection will be updated during create handler.

2023-03-14 21:30 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +  "readOnlyProperties": [
added more readOnlyProperties. but we skip some when we do the contract tests

2023-03-14 21:31 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +        "cloudformation:CreateStack"
as discussed setstackpolicy will be set duing create and update. we only need getStackpolicy for readhandler

2023-03-14 21:31 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +    "/properties/StackName"
addressed

2023-03-14 21:31 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +    "/properties/StackPolicyBody"
removed StackPolicy from writeONly

2023-03-14 21:31 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +      "type": "string"
changed to object

2023-03-16 22:27 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                        return awsResponse;
we only need to make this change if the previous/current property are different.  Otherwise we can skip the API call

2023-03-16 22:27 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                    })
we shoudl avoid the API call here too.  we should also ignore the exception where no updates are to be performed

2023-03-16 22:27 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/ReadHandler.java
> +        return ProgressEvent.progress(request.getDesiredResourceState(), callbackContext)
do we need to call GetTemplate to get the full template body?

2023-03-16 22:27 UTC, aygold92 commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +    "/properties/TemplateBody",
why aren't we using GetTemplate?

2023-03-16 22:27 UTC, aygold92 commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +        "cloudformation:ListStacks",
do we need ListStacks?

2023-03-16 22:27 UTC, aygold92 commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +      "type": "string"
this should be an object too

2023-03-22 22:15 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +      "type": "string"
Changed to object

2023-03-22 22:15 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +        "cloudformation:ListStacks",
removed it

2023-03-22 22:16 UTC, yingxnin commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +    "/properties/TemplateBody",
removed templatebody from writeOnly

2023-03-22 22:16 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/ReadHandler.java
> +        return ProgressEvent.progress(request.getDesiredResourceState(), callbackContext)
added getTemplate call in the read handler

2023-03-22 22:17 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                    })
We will keep the same as discussed. One example why we don't want to check because if TemplateURL doesn't change but the content changes.

2023-03-22 22:17 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +                        return awsResponse;
adding the check if changed, then call the updateTerminationProtection API, otherwise, skip

2023-03-24 16:25 UTC, aygold92 approved these changes

2023-03-24 16:25 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/UpdateHandler.java
> +        if(model.getEnableTerminationProtection() != null && !model.getEnableTerminationProtection().equals(previousModel.getEnableTerminationProtection()))
interesting use case if the customer removes termination protection from the template...  Honestly, I don't even know what that would mean, whether they want to disable it or just do nothing 🤔

2023-03-24 16:25 UTC, aygold92 commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +            }
I don't think this would ever happen on stabilization, but I suppose this is the right behavior at this point if it did? 🤔  Since you already did preexistence check.

2023-04-03 10:53 UTC, MalikAtalla-AWS commented on aws-cloudformation-stack/.gitignore
> +# macOS
This PR needs a title and a description

2023-04-05 00:36 UTC, weshuai commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +            case ROLLBACK_FAILED:
I think create stack can't have a failed status like "DELETE_COMPLETE", "DELETE_FAILED"?

2023-04-05 00:36 UTC, weshuai commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/DeleteHandler.java
> +            }
+1, I think existence check is not needed here

2023-04-05 00:36 UTC, weshuai commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/Translator.java
> +    if(model.getTemplateBody() != null && !model.getTemplateBody().toString().isEmpty()) {
SBS create stack activities do input validation at https://code.amazon.com/packages/AWS21StackBuilderService/blobs/37cbd207080783a82c36921110b86e0968836ab5/--/src/amzn/aws21/sbs/activities/utils/InputValidator.java#L134, should we add the same validation logic here?

2023-04-05 15:49 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/CreateHandler.java
> +            case ROLLBACK_FAILED:
I think this is just in case, for example. people initiate a create and then delete between the stablization check....I think it is not bad to put it here

2023-04-05 15:50 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/BaseHandlerStd.java
> +  public final ProgressEvent<ResourceModel, CallbackContext> handleRequest(
will update it.

2023-04-05 15:51 UTC, yingxnin commented on aws-cloudformation-stack/src/main/java/software/amazon/cloudformation/stack/Translator.java
> +    if(model.getTemplateBody() != null && !model.getTemplateBody().toString().isEmpty()) {
I think because this is just a wrapper outside of sbs and facade. it is necessary to do another check again? we can just fallback to the sbs check.

2023-04-05 16:39 UTC, weshuai approved these changes

2023-04-05 21:23 UTC, rushilrs121198 approved these changes

2023-04-05 22:17 UTC, zhaomicx approved these changes

2023-04-05 22:18 UTC, zhaomicx commented on aws-cloudformation-stack/aws-cloudformation-stack.json
> +        "cloudformation:DescribeStacks",
Note: this is backward incompatible with native Stack attribute retriever, which does not require any API calls to return the stack id on a Ref call.

2023-04-11 18:53 UTC, merged