ResourceDefaultVersion - added Primary ID TypeArn and made delete han…
aws-cloudformation/aws-cloudformation-resource-providers-cloudformation pull request #19
Opened 2020-10-02 02:33 UTC by ugudip

…dler idempotent. Also, ResourceVersion - removed conflicting version bugs

1. Added Primary ID for ResourceDefaultVersion
2. Resolved several bugs - version conflicts and exceptions
3. Made unit test changes, jacoco coverage >80%

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-05 05:06 UTC, tyangjie commented on aws-cloudformation-resourcedefaultversion/aws-cloudformation-resourcedefaultversion.json
> +    "TypeArn": {
rename "Arn" to "TypeVersionArn"?

2020-10-05 05:09 UTC, tyangjie commented on aws-cloudformation-resourcedefaultversion/aws-cloudformation-resourcedefaultversion.json
> +    "TypeArn": {
Rename "Arn" to "TypeVersionArn"?

2020-10-05 05:45 UTC, tyangjie requested changes

2020-10-05 05:45 UTC, tyangjie commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +          return ProgressEvent.progress(resourceModel, callbackContext);
if type arn is null from the template input, then create handler does nothing?

2020-10-05 05:45 UTC, tyangjie commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +        {
Use ```StringUtils.isNotEmpty```,  and please take care of spacing/formatting

2020-10-05 05:45 UTC, tyangjie commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +        if(!StringUtils.isNullOrEmpty(resourceModel.getArn())){
Use ```StringUtils.isNotEmpty```, and spacing

2020-10-05 12:23 UTC, benkehoe commented
Isn't it useful for resources to have a standardized "Arn" property, so as a user, I don't have to figure out what inevitably-inconsistent naming convention every particular resource provider decided to adopt for their Arn property? (I feel the name about "Name" as a property).

2020-10-05 21:54 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/aws-cloudformation-resourcedefaultversion.json
> +    "TypeArn": {
Yup, The Arn in line 6 actually represents the TypeversionArn, I can change that.

2020-10-05 22:42 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +          return ProgressEvent.progress(resourceModel, callbackContext);
The reason for writing it this way is because, we need to first generate the TypeArn and set that PrimaryId generated to the resource model back in the progress call chain. This makes cfn decide if it's an already existing resource or a new one. If TypeArn is null, we generate one and return an IN_PROGRESS event. This then calls the remaining part of the logic(setTypeDefaultVersion) and completes after a read handler is called.

2020-10-05 22:42 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +        {
Noted.

2020-10-07 02:01 UTC, ugudip commented
I made the following changes:
1. Made "Arn" as the Physical Id for ResourceDefaultVersion which represents the overall type(ex: arn:aws:cloudformation:us-west-2:336098619110:type/resource/Organization-Service-Resource11) and added it as a readOnly property
2. Changed the current "Arn" to "TypeVersionArn" which represents the Arn of the ResourceVersion. The user should now give "TypeVersionArn" in the template to refer ResourceVersion's Arn.
3. Kept the ResourceVersion's "Arn" as is because it represents the physical Id of the ResourceVersion and makes sense to keep it Arn.
3. Changed the Unit tests and code formatting.
4. Added a check to get the latest versionID in perdictArn() - bug fix

2020-10-09 18:46 UTC, tyangjie approved these changes

2020-10-12 23:06 UTC, jotompki commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +        if (StringUtils.isNullOrEmpty(resourceModel.getArn())) {
i feel like we should be using the callbackContext to set any sort of stateful things like the arn to indicate a transition. is the arn not being included in the initial input expected? what if someone includes this in their template? using the callbackContext to check if the arn has been set might avoid abusing the arn being set as some sort of state.

2020-10-12 23:06 UTC, jotompki commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +            // generating Arn from the TypeName and versionID
versionId isn't used to generate arn.

2020-10-12 23:06 UTC, jotompki commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +                            .makeServiceCall((setTypeDefaultVersionRequest, client) -> proxyClient.injectCredentialsAndInvokeV2(setTypeDefaultVersionRequest, proxyClient.client()::setTypeDefaultVersi
do we map the TypeNotFoundException that's thrown here to the notfound exception in the handler? if  a resource type doesnt exist and we try to set a default version, what happens?

2020-10-12 23:11 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +            // generating Arn from the TypeName and versionID
Sure, I will change the comment here, I actually meant when TypeName and VersionId are given as an input..

2020-10-13 16:56 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +        if (StringUtils.isNullOrEmpty(resourceModel.getArn())) {
Made changes.

2020-10-13 16:57 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
> +                            .makeServiceCall((setTypeDefaultVersionRequest, client) -> proxyClient.injectCredentialsAndInvokeV2(setTypeDefaultVersionRequest, proxyClient.client()::setTypeDefaultVersi
In that case, the resource creation fails anyway. But I added the check in the handle error clause to let Cfn know it's a NotFoundException.

2020-10-13 17:04 UTC, jotompki approved these changes

2020-10-13 17:10 UTC, merged