Initial commit for TypeVersion and TypeDefaultVersion resourceTypes -…
aws-cloudformation/aws-cloudformation-resource-providers-cloudformation pull request #39
Opened 2021-01-09 00:08 UTC by ugudip

… only schema

*Description of changes:*
Creating new generic resourceTypes AWS::CloudFormation::TypeVersion and AWS::CloudFormation::TypeDefaultVersion to support any Registry type(RESOURCE/MODULE). These two resourceTypes are also compatible with any new type in future.

This PR only contains Schema. The handlers included are all dummy for now. I will add handler implementation in a separate PR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-09 00:42 UTC, tyangjie approved these changes
reviewed schemas, LGTM

2021-01-11 22:37 UTC, jotompki requested changes

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/pom.xml
> +            <version>2.0.2</version>
```suggestion
            <version>2.0.3</version>
```

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/pom.xml
> +            <version>2.13.18</version>
```suggestion
            <version>2.15.19</version>
```

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/.rpdk-config
> +    "testEntrypoint": "software.amazon.cloudformation.typedefaultversion.HandlerWrapper::testEntrypoint",
```suggestion
    "testEntrypoint": "software.amazon.cloudformation.typedefaultversion.HandlerWrapper::handleRequest",
```

Contract testing uses the main entrypoint now. Better to change it here.

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typeversion/.rpdk-config
> +    "testEntrypoint": "software.amazon.cloudformation.typeversion.HandlerWrapper::testEntrypoint",
```suggestion
    "testEntrypoint": "software.amazon.cloudformation.typeversion.HandlerWrapper::handleRequest",
```

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +        ""
delete is no op?

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +      "description": "The Amazon Resource Name (ARN) of the type without the versionID. This is used to uniquely identify a TypeDefaultVersion",
👍

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typeversion/pom.xml
> +            <version>2.13.18</version>
same bump as above

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typeversion/pom.xml
> +            <version>2.0.2</version>
same version bump as above

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typeversion/aws-cloudformation-typeversion.json
> +        "s3:GetObject",
does this also work when encryption is enabled on the schema handler package? do we need kms permissions as well?

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +  "properties": {
need type here

2021-01-11 22:37 UTC, jotompki commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +        "TypeName",
is type also required here?

2021-01-11 22:43 UTC, ugudip commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +        ""
That's right, because defaultVersions cannot be deleted.

2021-01-11 22:43 UTC, ugudip commented on aws-cloudformation-typedefaultversion/pom.xml
> +            <version>2.0.2</version>
Made changes.

2021-01-11 22:43 UTC, ugudip commented on aws-cloudformation-typedefaultversion/.rpdk-config
> +    "testEntrypoint": "software.amazon.cloudformation.typedefaultversion.HandlerWrapper::testEntrypoint",
I see. Changed it.

2021-01-11 22:49 UTC, ugudip commented on aws-cloudformation-typeversion/aws-cloudformation-typeversion.json
> +        "s3:GetObject",
I don't think we need kms permissions, but I will keep this in mind while implementing handlers.

2021-01-11 23:05 UTC, ugudip commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +  "properties": {
Actually, you are right, we do need a Type for default Version as well. Will add it. Thanks for catching this..

2021-01-11 23:07 UTC, ugudip commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +        "TypeName",
yes it is. Added.

2021-01-11 23:08 UTC, srujithpoondla03 approved these changes
LGTM, reviewed only schemas.

2021-01-11 23:11 UTC, ugudip commented on aws-cloudformation-typedefaultversion/pom.xml
> +            <version>2.13.18</version>
Done

2021-01-11 23:30 UTC, wbingli requested changes
There are many merge conflicts. Could you resolve them?

2021-01-11 23:30 UTC, wbingli commented on aws-cloudformation-typedefaultversion/.rpdk-config
> +<<<<<<< HEAD
Oops...

2021-01-11 23:30 UTC, wbingli commented on aws-cloudformation-typedefaultversion/aws-cloudformation-typedefaultversion.json
> +<<<<<<< HEAD
oops, should not have such merge conflict

2021-01-11 23:30 UTC, wbingli commented on aws-cloudformation-typedefaultversion/docs/README.md
> +<<<<<<< HEAD
Still have merge conflict

2021-01-11 23:37 UTC, ugudip commented on aws-cloudformation-typedefaultversion/.rpdk-config
> +<<<<<<< HEAD
sorry, 1 min pls, it was a wrong commit.

2021-01-11 23:44 UTC, jotompki commented on aws-cloudformation-typeversion/aws-cloudformation-typeversion.json
> +        "s3:GetObject",
kms:Decrypt may be used when the schema handler package is encrypted

2021-01-11 23:47 UTC, ugudip commented on aws-cloudformation-typeversion/aws-cloudformation-typeversion.json
> +        "s3:GetObject",
Oh okay. Thanks.

2021-01-12 00:16 UTC, jotompki approved these changes

2021-01-12 02:39 UTC, wbingli approved these changes

2021-01-12 02:42 UTC, merged

2021-01-12 13:01 UTC, benkehoe commented
Hopefully this is not intended to be the sole support for future registry types. Having individual CloudFormation resource types that corresponds to registry types allows for CloudFormation users to create more semantically meaningful templates, easier linting and governance, and a host of other similar benefits.