Add list handler to ResourceDefaultVersion, remove TypeVersion and Ty…
aws-cloudformation/aws-cloudformation-resource-providers-cloudformation pull request #72
Opened 2021-06-23 01:54 UTC by ugudip

*Description of changes:*
Create ListHandler for ResourceDefaultVersion, removed TypeVersion and TypeDefaultVersion as they are not in use

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-23 18:29 UTC, cathlh requested changes

2021-06-23 18:29 UTC, cathlh commented on aws-cloudformation-resourcedefaultversion/aws-cloudformation-resourcedefaultversion.json
> +        "cloudformation:ListTypes"
This should be ListTypeVersions right?

2021-06-23 18:29 UTC, cathlh commented on aws-cloudformation-resourcedefaultversion/resource-role.yaml
> +                - "cloudformation:ListTypes"
ListTypeVersions

2021-06-23 19:08 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/aws-cloudformation-resourcedefaultversion.json
> +        "cloudformation:ListTypes"
yea, my bad, fixed it.

2021-06-23 19:21 UTC, cathlh commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/Translator.java
> +                        .arn(typeSummary.arn().substring(0, typeSummary.arn().lastIndexOf("/")))
does this exclude the version part of the arn? we want to return the versioned arn here i thought

2021-06-23 19:22 UTC, ugudip commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/Translator.java
> +                        .arn(typeSummary.arn().substring(0, typeSummary.arn().lastIndexOf("/")))
No, the arn for ResourceDefaultVersion is without the version. This is done to make it unique per resource.

2021-06-23 19:23 UTC, cathlh commented on aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/Translator.java
> +                        .arn(typeSummary.arn().substring(0, typeSummary.arn().lastIndexOf("/")))
got it, thanks for clarifying

2021-06-23 19:24 UTC, cathlh approved these changes

2021-06-24 20:32 UTC, rajdivya commented on aws-cloudformation-typedefaultversion/src/main/java/software/amazon/cloudformation/typedefaultversion/CallbackContext.java
> -
Why this and a bunch of other files being deleted?

2021-06-24 20:50 UTC, ugudip commented on aws-cloudformation-typedefaultversion/src/main/java/software/amazon/cloudformation/typedefaultversion/CallbackContext.java
> -
TypeDefaultVersion and TypeVersion were added before to deprecate existing Modules* and Resource* but later we decided to move on with separate ones, hence I am deleting Type* files as they are not used anywhere.

2021-06-24 20:54 UTC, rajdivya approved these changes

2021-06-24 20:54 UTC, merged